### ISSUE TITLE
Provider version given in the example is '1.1' but the provider version available is '0.1.1'

### ISSUE THREAD

**Issue by ghost** [NetApp/terraform-provider-netapp-gcp#14]
Hi there, 
             I just spotted this in the README, if a user ends up copying and pasting the provider declaration as is, it will not work.

Also, it looks like this should be updated for terraform 0.13.0

Thank you for all the effort!

--Toni

**Comment by wenjun666** [comment]
Hi Toni, we will update the README, and reflect the change eariler next week. thanks.

**Comment by jtaatj** [comment]
This has been fixed.

**Comment by ghost** [comment]
LGTM
