### ISSUE TITLE
"zone" attribute needs to be mandatory for CVS-software

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#21]
Currently, the "zone" attribute is optional:
https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume

If user is using CVS-software, "zone" is mandatory.

We might enforce this in the provider.

See #20

**Comment by lonico** [comment]
This was addressed internally.   An unrelated failure in an acceptance test is currently preventing us to push it into GitHub.

**Comment by lonico** [comment]
fixed by 3f0f4e5bebbb565d91e4dad553e759265aec6ea6
