### ISSUE TITLE
CVS-Software: Error when creating - No Snapshot policy given.

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#27]
When creating a volume on CVS (storage_class = "software), volume creation fails with error 

`Error: Error when creating - No Snapshot policy given.`

This can be avoided by specifying a snapshot_policy. If no automated snapshots are desired, one still needs to specify at least
```tf
 snapshot_policy {
    enabled = true
  }
```
in the netapp-gcp_volume resource to avoid the failure. This enables automatic snapshot creation without actually providing a schedule, which leads to no automatic snapshots being created.

This is different behaviour compared to CVS-Performance (storage_class = "hardware"), which works without adding the code above. NetApp CVS engineering needs to investigate.

This issue is for documentation and tracking purpose.

**Comment by lonico** [comment]
At this point, this looks like an API issue.

**Comment by okrause** [comment]
Closing. Please use workaround described above.
