### ISSUE TITLE
mount_point outputs failing after volume create

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#35]
Problem description:

```bash
$ cat provider.tf | grep -v '#'
provider "netapp-gcp" {
blabla
}

terraform {
  required_version = ">= 0.13"
  required_providers {
    netapp-gcp = {
      source = "NetApp/netapp-gcp"
      version = "~> 20.11.1"
    }
  }
}

$ cat volume.tf 
resource "netapp-gcp_volume" "gcp-volume" {
  provider = netapp-gcp
  name = var.volume_name
  region = var.region
  protocol_types = var.protocol
  network = var.network
  size = var.size
  service_level = var.service_level
  # storage_class: choose "software for CVS, choose "hardware" for CVS-Performance
  storage_class = var.storage_class
  # zone: For storage_class = "software" specification of zone is required
  # zone = var.zone

  snapshot_policy {
    enabled = false
  }

  export_policy {
    rule {
      allowed_clients = "0.0.0.0/0"
      access= "ReadWrite"
      nfsv3 {
        checked =  true
      }
      nfsv4 {
        checked = false
      }
    }
  }
}
$ cat outputs.tf 
# returns IP/hostname of CVS export, e.g. 10.194.0.4
output "server" {
  value       = netapp-gcp_volume.gcp-volume.mount_points[0].server
  description = "The server address of the cloud volume."
}

$ terraform apply -auto-approve
netapp-gcp_volume.gcp-volume: Creating...
netapp-gcp_volume.gcp-volume: Still creating... [10s elapsed]
netapp-gcp_volume.gcp-volume: Still creating... [20s elapsed]
netapp-gcp_volume.gcp-volume: Still creating... [30s elapsed]
netapp-gcp_volume.gcp-volume: Still creating... [40s elapsed]
netapp-gcp_volume.gcp-volume: Creation complete after 43s [id=6db68e55-74ff-f84c-73b7-e2bcc654df87]

Error: Invalid index

  on outputs.tf line 3, in output "server":
   3:   value       = netapp-gcp_volume.gcp-volume.mount_points[0].server
    |----------------
    | netapp-gcp_volume.gcp-volume.mount_points is empty list of object

The given key does not identify an element in this collection value.

$ terraform apply -auto-approve
netapp-gcp_volume.gcp-volume: Refreshing state... [id=6db68e55-74ff-f84c-73b7-e2bcc654df87]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

server = "10.194.0.68"
```

When specifying mount_point outputs at volume create, I get an error message. This used to work, looks like a regression.

Running the same terraform apply a second time (after volume was created), it works.

My assumption:
I assume the issue is related to the problem in #31.
Likely, volume creation uses "Describe all volumes" (/v2/projects/{projectNumber}/locations/{locationId}/Volumes) call, which doesn't return all fields.

To get all fields, an individual volume needs to be queried with a "Describe a volume" REST call (/v2/projects/{projectNumber}/locations/{locationId}/Volumes/{volumeId}). Terraform refresh is using this call.

I will investigate the next days.

Workaround:
Rerun terraform apply to get outputs populated.

**Comment by okrause** [comment]
Seems to an intermittent issue.

**Comment by lonico** [comment]
maybe a timing issue.   It sometimes take a long time to get a volume created.   Maybe we need to retry if the mount point data is not filled in.

**Comment by lonico** [comment]
Justin also found an issue related to retrying on spawn errors.  The API response code changed, and we had to adapt the code to support the new value.   Not sure if could explain the intermittent issue.  The code was released as 21.4.0.

**Comment by lonico** [comment]
Oliver, can we close this issue, or are you still seeing it?

**Comment by okrause** [comment]
I haven't really used this functionality since then. I cannot comment if it works reliable now or not. I am fine with closing, wil lreopen if I encounter it again.
