### ISSUE TITLE
Getting error "json: cannot unmarshal string into go struct field simpleexportpolicyrule.exportpolicy.rules.hasrootaccess of type bool"

### ISSUE THREAD

**Issue by ts9990** [NetApp/terraform-provider-netapp-gcp#39]
I am getting error while running terraform apply-

json: cannot unmarshal string into go struct field simpleexportpolicyrule.exportpolicy.rules.hasrootaccess of type bool 

even after changing "has_root_access "  -->  true , "true" , "on" , "false" , false , "off"

**Comment by wenjun666** [comment]
Can you update to the latest version? It's been fixed.

**Comment by lonico** [comment]
fixed with b236d0f8a92d2ff69fd16cce0c767253963dbeb3

The provider is published as 21.4.0
https://registry.terraform.io/providers/NetApp/netapp-gcp/latest
