### ISSUE TITLE
Cosmetic: Allow specification of service levels  "standard", "premium" and "extreme"

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#4]
When creating/updating a volume, a **service_level** parameter can be specified. Currently the provider allows to the values low/medium/high as service_levels, which reflects the CVS API. The CVS UI in GCP uses a different nomenclature (standard/premium/extreme).

For consistency between UI and TF provider, it would be good if the provider could (additionally to low/medium/high) allow using the UI names for the different service levels:
standard = low
premium = medium
extreme = high

**Comment by lonico** [comment]
Tracked internally as 2465

**Comment by lonico** [comment]
fixed with commit c46f7bc4c28dace8ca3e5dd26e065a5cf9754bdd
