### ISSUE TITLE
Netapp volume replication feature with terraform

### ISSUE THREAD

**Issue by jebasss** [NetApp/terraform-provider-netapp-gcp#40]
Terraform sample code for volume replication has only the source and destination configurations (terraform-provider-netapp-gcp/examples/gcp/volume_replication/volume-nfs.tf). The code for scheduled frequency at which interval the volume replication should happen is missing here. 

Moreover, the terraform code is not available in terraform hashicorp site as well (see below). I assume this feature is supported by terraform at present since this is in BETA release level.

https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume

Do we have any ETA on when this feature will be available in terraform hashicorp site?

**Comment by okrause** [comment]
Hello,
the example code is currently a stub. The code to setup volume replication doesn't exist in the provider, yet.

@lonico any guidance on when we will add code for volume replication?

**Comment by lonico** [comment]
We're still waiting for a green light on whether we should release this feature or not.
While we're able to create relationships, there are some issues when deleting them.

**Comment by lonico** [comment]
Please see https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume_replication

The code was published as 21.9.0.
