### ISSUE TITLE
Plugin did not respond, report it to plugin'd maintainer

### ISSUE THREAD

**Issue by aakash-ssh** [NetApp/terraform-provider-netapp-gcp#42]
Trying to spin a NetApp CVS through terraform, error is asking to report it to plugin'd maintainer. If i am using gcp console there isn't any issue.
 

Error: Plugin did not respond
│
│   with netapp-gcp_volume.gcp-volume,
│   on main.tf line 18, in resource "netapp-gcp_volume" "gcp-volume":
│   18: resource "netapp-gcp_volume" "gcp-volume" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-netapp-gcp_v20.10.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe34c71]

goroutine 67 [running]:
github.com/netapp/terraform-provider-netapp-gcp/gcp.resourceGCPVolumeCreate(0xc000314930, 0x1089aa0, 0xc0000a5830, 0x2, 0x1b23c60)
        github.com/netapp/terraform-provider-netapp-gcp/gcp/resource_netapp_gcp_volume.go:400 +0xdd1
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002a8d80, 0xc000100b90, 0xc0003c1ac0, 0x1089aa0, 0xc0000a5830, 0xf4d401, 0xc000450528, 0xc0003a4240)
        github.com/hashicorp/terraform@v0.12.28/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0002a9580, 0xc000243a00, 0xc000100b90, 0xc0003c1ac0, 0xc00055abc8, 0xc000288fd8, 0xf4f3a0)
        github.com/hashicorp/terraform@v0.12.28/helper/schema/provider.go:289 +0x99
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000288500, 0x13927c0, 0xc0000dd440, 0xc00027cf60, 0xc000288500, 0xc0000dd440, 0xc000677b78)
        github.com/hashicorp/terraform@v0.12.28/helper/plugin/grpc_provider.go:885 +0x8c4
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x106ade0, 0xc000288500, 0x13927c0, 0xc0000dd440, 0xc00027cf00, 0x0, 0x13927c0, 0xc0000dd440, 0xc0006eca00, 0x4aa)
        github.com/hashicorp/terraform@v0.12.28/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001800, 0x139da20, 0xc000210d80, 0xc00018ec00, 0xc000103ad0, 0x1ae9560, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000001800, 0x139da20, 0xc000210d80, 0xc00018ec00, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000345e0, 0xc000001800, 0x139da20, 0xc000210d80, 0xc00018ec00)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-netapp-gcp_v20.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by okrause** [comment]
Thank you for your error report. 
Please upgrade to the newest provider version (version = "~> 21.5.0" in the terraform block of your tf files) and see if the problem persists.

**Comment by aakash-ssh** [comment]
Classification: Confidential
Thanks Oliver, this error is subsided now by changing the version, However a new Error is there. Error: Error when creating - No Host found that is reachable. Trying to figure out. Thanks for the support.

Regards,
Aakash Sharma

**Comment by okrause** [comment]
This looks like a network issue and not related to terraform. My guess is that due to missing internet connectivity or firewalls, your terraform machine cannot reach the CVS API endpoint at https://cloudvolumesgcp-api.netapp.com

**Comment by aakash-ssh** [comment]
Classification: Confidential
Thanks Oliver, will look into this direction.

**Comment by okrause** [comment]
Hi @aakash-ssh, have you been able to resolve your problems? Can this issue be closed?

**Comment by aakash-ssh** [comment]
Classification: Confidential
Hi Oliver,

I was able to resolve the issue. Please go ahead and close the same.

Thanks,
Aakash

**Comment by okrause** [comment]
Hi Aakash,

please close it yourself, since I don't have the permissions to close it. Thank you.

**Comment by aakash-ssh** [comment]
Done, worked fine after changing the version.
