### ISSUE TITLE
Create an option to disable snapshot directory visibility

### ISSUE THREAD

**Issue by rpmduarte** [NetApp/terraform-provider-netapp-gcp#44]
Currently when creating a new cvs volume it defaults to make visible the snapshot directory.
it's breaking a few of the apps that we use, and after each new cvs volume is deployed we then have to go and manually change the option in the GCP console, could it be possible to add an option in the netapp-gcp_volume resource such as example:
     ...
      size = 1024
      service_level = "premium"
      volume_path = "deleteme-asapGO"
      snapshot_policy {
        enabled = true
        daily_schedule {
          hour = 10
          minute = 1
        }
 
A (to be added) property 
  snapshot_directory = false
would nicely fit in there.

**Comment by okrause** [comment]
Good ask. Makes a lot of sense.

The API does provide such an parameter:
`curl -s https://cloudvolumesgcp-api.netapp.com/swagger.json | 
jq '.definitions.Volume_v2.allOf[1].properties.snapshotDirectory'`

We should include that option into the provider. Will discuss it with the maintainers.

**Comment by lonico** [comment]
fixed with 843b56313226e587c9e8b56ab54f749a0e805531
Published as 21.9.0.
