### ISSUE TITLE
Add support for authenticated users

### ISSUE THREAD

**Issue by ms185570** [NetApp/terraform-provider-netapp-gcp#46]
When running Terraform locally or via Cloud Build the execution is being done with an authenticated user account which prevents the need to generate and store keys. Can this provider be updated to support that for operations so that a key doesn't have to be persisted?

**Comment by lonico** [comment]
Are you referring to this?
https://cloud.google.com/docs/authentication/end-user

The last time we checked with the GCP team, this was not supported for CVS.  They strongly recommended to use Service Accounts.

**Comment by ms185570** [comment]
I am using a Service Account in Cloud Build but my Cloud Build service account is impersonating my Terraform service account. In order to use that account, I have to generate keys for that service account and store them somewhere which is much less secure.

**Comment by okrause** [comment]
We are aware of this requirement and it is being discussed. Today, service account impersonation isn't supported and we don't have a timeline for it yet.
The way to do it meanwhile is to pass the a service account json key. This can be done either as file, or as credentials string.
Credential string is basically the content of a JSON key file in a TF string.

**Comment by martinlmccourt** [comment]
Any chance this could be looked at? Other providers use my credentials as logged in with the _gcloud login_ command. To be clear the other providers are using [application default credentials](https://cloud.google.com/sdk/gcloud/reference/auth/application-default) without a service account.

**Comment by okrause** [comment]
> Any chance this could be looked at? Other providers use my credentials as logged in with the _gcloud login_ command. To be clear the other providers are using [application default credentials](https://cloud.google.com/sdk/gcloud/reference/auth/application-default) without a service account.

The requirement is understood. We making slow progress, but no conclusion on do-ability and timelines yet.

**Comment by okrause** [comment]
Good news. Yesterday release 22.2.0 was released on GitHub (not in TF registry yet). It added support for "Service Account Impersonation".
How to use it:
in the provider section, specify the name of a service account which has roles/netappcloudvolumes.admin, using the service_account keyword, e.g.:

service_account = "cvs-admin@my-project-id.iam.gserviceaccount.com"

Next, give your ADC user (see https://cloud.google.com/sdk/gcloud/reference/auth/application-default and https://google.aip.dev/auth/4110) roles/iam.serviceAccountTokenCreator on the service account:

gcloud iam service-accounts add-iam-policy-binding \
cvs-admin@my-project-id.iam.gserviceaccount.com \
--member=user:my_ADC_USER@example.com \
--role=roles/iam.serviceAccountTokenCreator

Now, the 22.2.0 provider will use service account impersonation to do CVS API calls.
