### ISSUE TITLE
Multizone volume doesn't work

### ISSUE THREAD

**Issue by pgarevalo** [NetApp/terraform-provider-netapp-gcp#48]
I am unable to create a multi-zone volume using the 'regional_ha = true' attribute. The zone is mandatory due to the approved issue #21 and it should be modified with something like this:

https://github.com/NetApp/terraform-provider-netapp-gcp/blob/master/gcp/resource_netapp_gcp_volume.go#L421

`// If storage class is 'software', zone or regionalHA is mandatory`
`if volume.StorageClass == "software" && ((volume.Zone == "" && volume.regionalHa == "") || (volume.Zone != "" && volume.regionalHa != "")) {`
`log.Print("Error creating volume")`
`return fmt.Errorf("If storage_class is software, zone or regionalHA is mandatory")`
`}`

Note that TF creates a **single zone** volume using both 'zone' and 'regional_ha' attributes, and a **multizone** volume is created successfully with the same both attributes using Rest API calls.

**Comment by okrause** [comment]
Yes, I realised that on Friday also and want to give it some investigation this week.

**Comment by pablogarciaarevalo** [comment]
I was debugging a little and it seems that Terraform doesn't send the '_regional_ha_' argument when create the Rest API call. I think that the issue could be that the '_regional_ha_' argument is not defined here: https://github.com/NetApp/terraform-provider-netapp-gcp/blob/master/gcp/data_source_gcp_volume.go
