### ISSUE TITLE
Provide Terraform Outputs for mount target

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#5]
User story:

A user creates a new volume through this TF provider. After the volume is created, the user wants to mount/map the volume to a virtual machine, likely programmatically. To do this, the provider needs to export the NFS mount point or SMB share UNC path. A user can then use this data to create terraform outputs.

Example:
NFSv3 : 10.194.0.36:/gifted-cocky-wozniak
SMB : \\\\cvssmb-0383.cvsdemo.local\nervous-friendly-lovelace

To be able to create an output, the provider needs to able to query/provide the mount target. It is preferable if export path and server IP are provided separately.
 
A quick look at https://cloudvolumesgcp-api.netapp.com/swagger.json suggests that MountPoint_v2.export and MountPoint_v2.server and potentially MountPoint_v2.protocolType are likely the fields of interest.

**Comment by lonico** [comment]
Tracked internally as 2483

**Comment by okrause** [comment]
Was added in c3d8c282d7725151eef26f7ed3b2867c0b65013a

This issue is solved.
