### ISSUE TITLE
Add mount point to output when creating volumes

### ISSUE THREAD

**Issue by ms185570** [NetApp/terraform-provider-netapp-gcp#50]
We would like to output the mount point for created volumes so they can easily be used elsewhere.

**Comment by okrause** [comment]
It's already available. Please have a look at the [examples](https://github.com/NetApp/terraform-provider-netapp-gcp/blob/master/examples/gcp/volume/advanced/outputs.tf)

**Comment by okrause** [comment]
@ms185570 Did the examples above help resolve the issue? If yes, please close this issue.
