### ISSUE TITLE
future of snap_reserve?

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#54]
The provider allows to set the volume option snap_reserve. snap_reserve allows to hide a given percentage of space from the user. A 10 TiB volume with 20% snap_reserve will only show 8 TiB to the user (e.g. via df).

Unfortunately, a lot of space reporting counters start to become unreliable as soon as snap_reserve <> 0 is set. 0 is the default and setting it to something else might cause issues for users. Fortunately, very, very few users seem to use it so far.

I want to have a discussion:
- Should we remove that option to protect users from potential issues?
- Should we put explicit warnings in the documentation so users are warned?
- Should we remove it from the documentation and hide it, so only experienced pro-users will use it? Issue is likely auto-generated documentation.

Opinions?

**Comment by carchi8py** [comment]
We will combine all the snap_reserve stories in to #55
