### ISSUE TITLE
CVS-SO: snap_reserve setting does not persist

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#55]
provider 21.10.1
For CVS- Software volumes, the TF provider reports changes to snap_reserve every single apply run.

In my tests, I don't set snap_reserve. Every follow-on "terraform apply" run reports:

`netapp-gcp_volume.gcp-volume-nfs: Refreshing state... [id=35467bf9-aaa3-2789-b067-a021968df56c]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # netapp-gcp_volume.gcp-volume-nfs has changed
  ~ resource "netapp-gcp_volume" "gcp-volume-nfs" {
        id                       = "35467bf9-aaa3-2789-b067-a021968df56c"
        name                     = "okcvs-so"
      ~ size                     = 1024 -> 2000
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions
to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # netapp-gcp_volume.gcp-volume-nfs will be updated in-place
  ~ resource "netapp-gcp_volume" "gcp-volume-nfs" {
        id                       = "35467bf9-aaa3-2789-b067-a021968df56c"
        name                     = "okcvs-so"
      ~ size                     = 2000 -> 4000
      ~ snap_reserve             = 20 -> 0
        # (11 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
netapp-gcp_volume.gcp-volume-nfs: Modifying... [id=35467bf9-aaa3-2789-b067-a021968df56c]
netapp-gcp_volume.gcp-volume-nfs: Modifications complete after 10s [id=35467bf9-aaa3-2789-b067-a021968df56c]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
`

Although I didn't set snap_reserve, the provider thinks it is set to 20. Either the API reports 20, no matter what the provider sets, or the provider is doing something wrong when setting it.

We need to investigate.

**Comment by okrause** [comment]
I managed to do some tests.
Observations:
- I can send snapReserve=20 and snapReserve=0 to the API without getting an error. All other values I tried (10, 21, 50) returned an error.
- Whatever I send (e.g. 0), the value sticks at 20.
- Although the setting sticks at 20, the behaviour observed through the client (df -h) is snapReserve=0.

Conclusion:
This setting is defunct for CVS-SO.

Recommendation:
In #54 I opened up the discussion on what to do with snapReserve going forward. On CVS-Performance, it might create unexpected issues/confusion for uneducated users, on CVS-SO it is defunct. With this knowledge in mind, I strongly vote to remove support for snapReserve at all. It will fix the state bug for CVS-SO and prevent CVS-Performance users from trouble.

**Comment by wenjun666** [comment]
@lonico, what do you think?

**Comment by lonico** [comment]
I'm fine with removing this option.  It's the simplest solution. 

But if the option is omitted in the configuration, do we have a problem?  I would think if the option is absent it should be ignored.  So could it be a bug in the way we are handling this option?

**Comment by wenjun666** [comment]
The only scenario I can think of is: when someone uses snap_reserve and upgrade to the newer version, which snap_reserve is removed from option. They need to remove it from the resource file. snap_reserve will be left in the state file, but just as an orphan attribute, it will be ignored.

**Comment by carchi8py** [comment]
Devops 4850 has been made for this issue.

**Comment by wenjun666** [comment]
snap_reserve option removed in v22.4.0
