### ISSUE TITLE
CVS-SO: Incorrect size state tracking

### ISSUE THREAD

**Issue by okrause** [NetApp/terraform-provider-netapp-gcp#56]
provider 21.10.1

I am running multiple resize operations in a row.
First observation: TF provider returns, although the resize operation is still ongoing. Usually not an issue, but here the second invocation can return an error (maybe worth an extra issue).
Next observation: I am waiting for the resize to finish, but state for "size" seems to gets confused. A terraform apply operation shows:

`netapp-gcp_volume.gcp-volume-nfs: Refreshing state... [id=35467bf9-aaa3-2789-b067-a021968df56c]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # netapp-gcp_volume.gcp-volume-nfs has changed
  ~ resource "netapp-gcp_volume" "gcp-volume-nfs" {
        id                       = "35467bf9-aaa3-2789-b067-a021968df56c"
        name                     = "okcvs-so"
      ~ size                     = 1024 -> 2000
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions
to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # netapp-gcp_volume.gcp-volume-nfs will be updated in-place
  ~ resource "netapp-gcp_volume" "gcp-volume-nfs" {
        id                       = "35467bf9-aaa3-2789-b067-a021968df56c"
        name                     = "okcvs-so"
      ~ size                     = 2000 -> 4000
      ~ snap_reserve             = 20 -> 0
        # (11 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
netapp-gcp_volume.gcp-volume-nfs: Modifying... [id=35467bf9-aaa3-2789-b067-a021968df56c]
netapp-gcp_volume.gcp-volume-nfs: Modifications complete after 10s [id=35467bf9-aaa3-2789-b067-a021968df56c]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
`

So the size of the volume is 2000 and I am changing it to 4000. But the local state still believes it is 1024, the prior size. Looks like a volume size change TF operation doesn't track the correct state. This is likely related to the async operation reported above. Likely we still have a prior state if we finish to early and don't wait for the operation to finish.

We likely should wait for the operation to finish, before returning. Otherwise, we can run into issues like:
- wrong states
- next invocation will fail due prior operation still ongoing

**Comment by okrause** [comment]
Did some investigation. The resize of a CVS-SO volume can take multiple minutes. While the resize is happening, the lifeCycleState is "updating" and quotaInBytes reports to old size. Only when lifeCycleState switches to "available", quotaInBytes reports the new size. Since the TF apply returns before the update (=the resize operation) is finished, the state cannot report the correct size.

Best fix is likely to wait fo the operation to finish, before we return. Will also fix the "Error: code: 409, message: Error updating volume - Volume is already transitioning between states" issue. It happens if the user tried to run another change before the previous one is finished.

**Comment by wenjun666** [comment]
I look into the read function of the volume, while the volume is either creating or updating, we wait for 5 minutes for completion, after 5 minutes, the read function continues disregarding it's finished or not. Looks like to me the wait time is not long enough.

**Comment by lonico** [comment]
Makes sense to me to wait longer, if we see the operation is still in progress.  Though 5 minutes to create a volume is pretty long.  Is this the first volume?  Or it does not matter?

**Comment by okrause** [comment]
Required backend infrastructure is created lazily on first volume creation in that region. So first volume always takes much longer.
I don't have hard numbers at hand, but here some guesses for first volume creation:
CVS-Performance: typically 5min. Max 10min.
CVS: typically around 12min. Max 15-20min.
If volume being created is SMB and AD server is not reachable, I have seen CVS volume creation running up to 45min, until it times out with an error.

**Comment by wenjun666** [comment]
Issue resolves with v22.1.0
