### ISSUE TITLE
Some required arguments should not be mandatory when creating volumes using Storage Pools

### ISSUE THREAD

**Issue by pgarevalo** [NetApp/terraform-provider-netapp-gcp#63]
The below terraform code should work to create a CVS volume using an existing Storage Pool.

```
resource "netapp-gcp_volume" "gcp-cvs-sw-volume" {
  volume_name = "example"
  size = 5
  pool_id = "58ab3dbf-15b0-66ac-ff4f-cdabd59cdc5c"
  protocol_types = ["NFSv3"]
  storage_class = "software"
}
```
However, the next arguments are still required. These information is already provided creating the Storage Pool and should not be mandatory when storage_class is software.
- network 
- region
- zone

**Comment by pgarevalo** [comment]
this issue is coming by the public CVS API

**Comment by lonico** [comment]
is the pool id guaranteed to be unique?

**Comment by pgarevalo** [comment]
Yes, pool id is unique. However, forget it as these required parameters are required by CVS API. For that reason I closed the issue.

**Comment by okrause** [comment]
poolId is supposed to be unique. But since all pools are managed on a regional level and there is no global coordination, there is an incredible small chance that there are UUD collisions for all kind of resources. To be super save, (region, poolId) is the relevant, unique tuple.
