### ISSUE TITLE
Add parameters required in AD connection

### ISSUE THREAD

**Issue by Mithun2507** [NetApp/terraform-provider-netapp-gcp#65]
1. The current AD connection resource does not have parameter to specify the Active Directory Connection Type. 
When creating the AD connection using the provider resource "netapp_gcp_active_directory" the connection type is left blank.
 we need to add "label" parameter to specify the Connection type is CVS or CVS-Performance

2. The "AD server Name" parameter  in the Kerberos Realm Details is also not added in the provider resource 

With both the parameters added to the provider resource "netapp_gcp_active_directory" we can manage the ad connection via terraform code.

**Comment by wenjun666** [comment]
Feature added in v22.6.0
