### ISSUE TITLE
netapp/netapp-gcp does not support resource type "netapp-gcp_storage_pool"

### ISSUE THREAD

**Issue by arindam-b** [NetApp/terraform-provider-netapp-gcp#66]
I am following the page: https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/storage_pool
Trying to storage pool.

Here is the provider:

```
# Install provider from terraform register, only available for version 0.13 and above.
terraform {
  required_providers {
    netapp-gcp = {
      source = "NetApp/netapp-gcp"
      version = "20.10.0"
    }
  }
}

# Configure the NetApp_GCP Provider
provider "netapp-gcp" {
  project         = var.project_id
}

resource "netapp-gcp_storage_pool" "storage-pool" {
  name = format("%s-%s-%s", var.prefix, var.environment, var.storage_pool)
  region = var.region
  zone = var.zone
  network = var.network
  size = 1024
  service_level = "StandardSW"
  storage_class = "software"

  billing_label {
      key = "client"
      value = "myclient"
    }
}

```

This is exactly same as what is mentioned in the site. But when I ran. it throws error as:

>
╷
│ Error: Invalid resource type
│
│   on storagepool.tf line 1, in resource "netapp-gcp_storage_pool" "storage-pool":
│    1: resource "netapp-gcp_storage_pool" "storage-pool" {
│
│ The provider netapp/netapp-gcp does not support resource type "netapp-gcp_storage_pool".
╵

any clue?

**Comment by okrause** [comment]
Hi, you are using provider version 20.10.0 which is from 2020. Use the latest version 22.6.0.

You will find some examples on how to use StoragePools here: https://github.com/NetApp/terraform-provider-netapp-gcp/tree/master/examples/gcp/storage_pool (still using the prior version. Just use the newer one instead),

**Comment by arindam-b** [comment]
Thanks.
