### ISSUE TITLE
how to provide security style as unix/NTFS using terraform while we provision netapp cvs with dual protocol in GCP

### ISSUE THREAD

**Issue by ajinkyajoshi** [NetApp/terraform-provider-netapp-gcp#81]

**Comment by ajinkyajoshi** [comment]
I don't see any attributes option for security style

**Comment by okrause** [comment]
You are correct. The provider currently doesn't support selecting the security style.

**Comment by ajinkyajoshi** [comment]
So how do I provision CVS volumes with Unix security using terraform..is there any alternative? Also what unix permissions indicates then..as then are to be used when protocol is unix..is there any way that that security style can be added to tf?

**Comment by ajinkyajoshi** [comment]
Can it be added in tf as it is required for dual cvs

**Comment by ajinkyajoshi** [comment]
also how do I create volume from snapshot..I can't see option to add snapshot id

**Comment by ajinkyajoshi** [comment]
so the use case is on console we see option for creating volume from snapshot, in terraform I don't see that option, how do i used snapshot id in cvs module

**Comment by ajinkyajoshi** [comment]
I am still getting error for security style saying it is not expected here

**Comment by lonico** [comment]
Yes, we need to update the provider.  The change is under review internally, and we'll need to publish a new version.

**Comment by ajinkyajoshi** [comment]
ok.. do we have ETA on both the changes to be implemneted?

**Comment by ajinkyajoshi** [comment]
hi @lonico do we have any update on when this change would be released

**Comment by lonico** [comment]
We're in the process of merging this PR to support `security_style`.

We had some unexpected issues with our internal validation pipelines.  Hopefully, this will be solved in a couple of days.

**Comment by ajinkyajoshi** [comment]
thanks @lonico for update, do we have same ETA for snapshot id getting tracked in different issue?

**Comment by okrause** [comment]
This feature is now available in release v22.12.0.
Use "security_style" = "unix" or "ntfs".

Please give it a try and close the issue if it works for you.
