### ISSUE TITLE
how do I create volume from snapshot..I can't see option to add snapshot id

### ISSUE THREAD

**Issue by ajinkyajoshi** [NetApp/terraform-provider-netapp-gcp#84]
how do I create volume from snapshot.. I can't see option to add snapshot id.

**Comment by lonico** [comment]
Yes, we don't have this option.
I'll create an internal story to track this,

**Comment by lonico** [comment]
DEVOPS-5657

**Comment by okrause** [comment]
This feature is now available in release v22.12.0. See https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume#snapshot_id

Please give it a try and close the issue if it works for you.

**Comment by okrause** [comment]
Added in commit aadcbc1da56899fd0704fb5e1ee4e09eb18f08c2, which is included in release 23.1.0.
