### ISSUE TITLE
Error creating/modifying volumecode: 400, message: Modification of Root Access is not available for SO volumes

### ISSUE THREAD

**Issue by manuiade** [NetApp/terraform-provider-netapp-gcp#90]
Hello,

I'm using the provider (latest version 23.4.0) to manage a GCP Netapp CVS volume. Here's the code to reproduce the error:

```
terraform {
  required_providers {
    netapp-gcp = {
      source  = "NetApp/netapp-gcp"
      version = ">= 23.4.0"
    }
  }
}

resource "netapp-gcp_storage_pool" "nfs_cvs_sp" {
  name           = "cvs-pool"
  region         = "europe-west1"
  zone           = "europe-west1-b"
  secondary_zone = "europe-west1-c"
  network        = "default"
  size           = 1024
  service_level  = "ZoneRedundantStandardSW"
  storage_class  = "software"
}

resource "netapp-gcp_volume" "nfs_cvs" {
  name                     = "cvs-volume"
  pool_id                  = netapp-gcp_storage_pool.nfs_cvs_sp.id
  size                     = 128
  volume_path              = "test"
  region                   = netapp-gcp_storage_pool.nfs_cvs_sp.region
  zone                     = netapp-gcp_storage_pool.nfs_cvs_sp.zone
  network                  = netapp-gcp_storage_pool.nfs_cvs_sp.network
  regional_ha              = true
  storage_class            = "software"
  service_level            = "standard"
  delete_on_creation_error = true
  protocol_types           = ["NFSv3"]
  export_policy {
    rule {
      access          = "ReadWrite"
      allowed_clients = "10.0.0.0/8"
      has_root_access = true
      nfsv3 {
        checked = true
      }
      nfsv4 {
        checked = false
      }
    }
  }
  unix_permissions = "0755"
}
```

When creating the volume using an export policy, the creation fails with the following error:

`Error: code: 400, message: Modification of Root Access is not available for SO volumes`

What else I've tried for the option which seems to throw the error, with the same result:

- setting _has_root_access_ to _true_
- setting _has_root_access_ to null

So the workaround is to create the volume commenting the export policy, adding it manually from GCP Cloud Volumes page, then uncomment the export policy to have Terraform not seeing any changes.

Then if I try to change something from the policy (IP range for example) the apply of modifications fails again with the same error.

From the [GCP documentation](https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-nfs-volumes#disable_root_access_to_the_volume) I see the following regarding the root access option:

**This option is only available for volumes of the CVS-Performance service type**

It seems to be something that has recently changed on GCP, since I have older volumes with this option used also for CVS volume types. I can also confirm that on GCP side there is no way to set this option for an existing CVS volume or a new one.

So I believe that the provider should completely remove the _has_root_access_ option to avoid request creation/update errors.

Thank you very much for your help.

**Comment by okrause** [comment]
Hi  @manuiade,

thank your for your error report. As you correctly stated, only CVS-Performance supports that option.

The CVS service type doesn't support it. Every export on it has_root_access = true all the time.

We don't want to bake every corner case into the provider itself. Sometimes we just have to rely on the error the APi is returning. This in one of such cases. We need to support the has_root_access parameter for CVS-Performance volumes and didn't include extra code for CVS service tier volumes. We would need to error out anyway if the user specifies it in that case. Wo why not use the error from the API itself versus adding a lot of code to make it fail a bit more gracefully.

That's a long way to say: We will not change this in the near future. Just leave that parameter away for CVS-SO volumes.

**Comment by okrause** [comment]
@manuiade I learned more about the issue. Looks like the API so far silently ignored that parameter for CVS-SO volumes. With a recent upgrade it started to reject the parameter, which makes CVS-SO volume with an NFS export policy creation fail.
We need a few days to investigate.

**Comment by paavan-gopala-reddy** [comment]
Please address this issue asap as we have a major road block because of this failure for SO Volumes.

Adding @rahulvunnam

**Comment by manuiade** [comment]
Hi @okrause,

thanks for the reply. That was exactly what I intended. For the CVS-SO the API started to reject the possibility to use this parameter, so even not specifying it from the provider it throws the error.

Please let me know when you have further updates.

**Comment by okrause** [comment]
Update: We want to release an updated provider which works around the API change. @wenjun666 is working on it, no timeline yet.

**Comment by manuiade** [comment]
Hello @okrause,

are there any news on the update?

**Comment by okrause** [comment]
@manuiade If am not tracking this closely, but looking into the repo I see that this is supposed to be fixed in 23.11.0. https://github.com/NetApp/terraform-provider-netapp-gcp/blob/master/CHANGELOG.md
Please try again with 23.11.0.

**Comment by manuiade** [comment]
Hello @okrause, I tried it and now the creation/modfication is working correctly, but there is just another small issue.
Launching another plan without changing anything in the code,  the provider always tries to modify the volume in the following way:

`

      - export_policy {
          - rule {
              - access               = "ReadWrite" -> null
              - allowed_clients      = "10.70.0.0/24" -> null
              - has_root_access      = "true" -> null
              - kerberos5_readonly   = false -> null
              - kerberos5_readwrite  = false -> null
              - kerberos5i_readonly  = false -> null
              - kerberos5i_readwrite = false -> null
              - kerberos5p_readonly  = false -> null
              - kerberos5p_readwrite = false -> null

              - nfsv3 {
                  - checked = true -> null
                }

              - nfsv4 {
                  - checked = false -> null
                }
            }
        }
      + export_policy {
          + rule {
              + access               = "ReadWrite"
              + allowed_clients      = "10.70.0.0/24"
              + kerberos5_readonly   = false
              + kerberos5_readwrite  = false
              + kerberos5i_readonly  = false
              + kerberos5i_readwrite = false
              + kerberos5p_readonly  = false
              + kerberos5p_readwrite = false

              + nfsv3 {
                  + checked = true
                }

              + nfsv4 {
                  + checked = false
                }
            }
        }
`

The code to reproduce is the same I shared at the beginning, except I have removed the attribute `has_root_access` from the declaration. Trying to set it to `null` explicitly has the same effect.

**Comment by okrause** [comment]
That's not good. It means the provider is doing a bad job tracking the state of the parameter.

@wenjun666 Looks like the API doesn't like the `has_root_access ` parameter on write (create/update), but returns it as `has_root_access = true` on reads. That poisons the local state, which in turn makes TF think it needs to update the rule.
Here the output of a volume created with aboves definition:
```tf
{'created': '2024-01-24T16:28:40.024Z',
 'lifeCycleState': 'available',
 'lifeCycleStateDetails': 'Available for use',
 'name': 'cvs-volume',
 'ownerId': 'b6055c56-6345-11ec-b607-72df95dd8674',
 'region': 'europe-west1',
 'volumeId': '4e4ca39d-efaa-4d43-2e62-f754d34a4d48',
 'zone': 'europe-west1-b',
 'billingLabels': None,
 'creationToken': 'test',
 'encryptionType': 'ServiceManaged',
 'exportPolicy': {'rules': [{'access': 'ReadWrite',
    'allowedClients': '10.0.0.0/8',
    'hasRootAccess': 'true',
    'kerberos5ReadOnly': {'checked': False},
    'kerberos5ReadWrite': {'checked': False},
    'kerberos5iReadOnly': {'checked': False},
    'kerberos5iReadWrite': {'checked': False},
    'kerberos5pReadOnly': {'checked': False},
    'kerberos5pReadWrite': {'checked': False},
    'nfsv3': {'checked': True},
    'nfsv4': {'checked': False}}]},
 'inReplication': False,
 'isDataProtection': False,
 'jobs': [],
...
 'snapshotDirectory': True,
 'storageClass': 'software',
 'timezone': 'GMT',
 'unixPermissions': '0755',
 'usedBytes': 303104}`

```

The fix is incomplete ...

**Comment by manuiade** [comment]
Hello @okrause,

are there any news on the fix?

**Comment by okrause** [comment]
Hi @manuiade. We released a new version. It is supposed to fix the issue you reported. Can you please check?

**Comment by manuiade** [comment]
Hello @okrause,

it looks like everything is working fine now.
Thank you very much for your support.
